package com.wildlife.fody.domain.enumeration;

/**
 * The BirdBehaviourType enumeration.
 */
public enum BirdBehaviourType {
    FLEW_AWAY_FROM_SITE, IN_NEST_SITE, PERCHING, FLYING, BEGGING_TO_MALE, FED_BY_MALE, ALLOPREENING_MALE, COPULATION_WITH_MALE, FEEDING_THE_FEMALE, ALLOPREENING_FEMALE, COPULATION_WITH_FEMALE, BRINGING_FOOD_ITEM, FEEDING, HUNTING, DEFENDING_NEST_SITE, CHASING_OTHER_MK, FIGHTING_OTHER_MK, CHASING_COMPETITORS, FIGHTING_COMPETITORS, INTERACTION_WITH_CHICKS, INTERACTION_WITH_FLEDGLINGS, CIRCLING_DISPLAYING_ABOVE_SITE
}
