package com.wildlife.fody.domain.enumeration;

/**
 * The FeedingObservationOutcomeType enumeration.
 */
public enum FeedingObservationOutcomeType {
    UNKNOWN, REMAINS_IN_NEST_SITE, REMAINS_NEAR_NEST_SITE, PASSED_TO_FEMALE, EATEN_BY_FEMALE, CACHED_BY_MALE, CACHED_BY_FEMALE, EATEN_BY_MALE, PASSED_TO_CHICKS, PASSED_TO_FLEDGLINGS, NOT_DELIVERED_TO_CHICKS_ACCESSING, NOT_DELIVERED_TO_CHICKS_RINGING, NOT_DELIVERED_TO_FEMALE_ACCESSING
}
