package com.wildlife.fody.domain.enumeration;

/**
 * The NestSiteType enumeration.
 */
public enum NestSiteType {
    BAMBOUS_VIRIEUX_3, CAMIZARD_CHARIZARD_CLIFF, CHAMPAGNE_CLIFF, CHIMNEY_CLIFF, DOMAINE_DE_LETOILE_2, DOMAINE_DE_LETOILE_3, DOMAINE_DE_LETOILE_4, DOMAINE_DE_LETOILE_5, DOMAINE_DE_LETOILE_8, DOMAINE_DE_LETOILE_9, DOMAINE_DU_CHASSEUR_5, DOMAINE_DU_CHASSEUR_7, DOMAINE_DU_CHASSEUR_8, DOMAINE_DU_CHASSEUR_CABIN, DOMAINE_DU_CHASSEUR_CAR_PARK, DOMAINE_DU_CHASSEUR_OFFICE, DOMAINE_DU_CHASSEUR_PLASTIC, EAST_ROCK, FERNEY_1, FERNEY_10, FERNEY_11, FERNEY_12, FERNEY_13, FERNEY_14, FERNEY_2A, FERNEY_2C, FERNEY_3, FERNEY_4, FERNEY_5, FERNEY_6, FERNEY_7, FERNEY_8, FERNEY_9, FERNEY_CLIFF, FERNEY_DUPONT, FERNEY_ENCLOSURE, FERNEY_INGAM, FERNEY_MIDDLE, FERNEY_REDUIT, LE_VALLON_13, LE_VALLON_6, MAURITANIA, MOUNT_CAMIZARD_1A, MOUNT_CAMIZARD_2A, MOUNT_CAMIZARD_2B, MOUNT_CAMIZARD_4, MOUNT_CAMIZARD_5, NEW_HOPE, OWENS_HOUSE, PETIT_FOND_1, PETIT_FOND_2, PETIT_PARC, POWER_STATION_CLIFF, RICHE_EN_EAU_11, RICHE_EN_EAU_13, RICHE_EN_EAU_2, RICHE_EN_EAU_3, RICHE_EN_EAU_4, RICHE_EN_EAU_9, UNDETECTED, VALLEE_DE_LEST, YLANG_CHASSE, YLANG_FOREST, ISENDGAARD, DRAGONS_VIEW, KOALA_CLIFF, COPSHOP_CLIFF, CAT_AND_MOUSE
}
