package com.wildlife.fody.domain.enumeration;

/**
 * The PreySpeciesType enumeration.
 */
public enum PreySpeciesType {
    UNKNOWN, PHELSUMA_SPP, PHELSUMA_CEPEDIANA, PHELSUMA_ORNATA, PHELSUMA_GUMBEAUI, PHELSUMA_ROSAGULARIS, HOUSE_GECKO, AGAMID_LIZARD, GREY_WHITE_EYE, MADAGASCAR_FODY, RED_WHISKERED_BULBUL, WAXBILL, ZEBRA_DOVE, YELLOW_FRONTED_CANARY, ASIAN_MUSK_SHREW, BLACK_RAT, BROWN_RAT, DRAGONFLY, STICK_INSECT, CICADA
}
