export const enum BoxConditionType {
  GOOD = 'GOOD',

  NEEDS_FIXING = 'NEEDS_FIXING',

  NEEDS_REPLACING_NEXT_SEASON = 'NEEDS_REPLACING_NEXT_SEASON',

  NEEDS_REPLACING_IMMEDIATELY = 'NEEDS_REPLACING_IMMEDIATELY',
}
