export const enum BreedingOutcomeType {
  ONGOING = 'ONGOING',

  FLEDGED = 'FLEDGED',

  FLEDGED_EGG_STAGE = 'FLEDGED_EGG_STAGE',

  FLEDGED_CHICK_STAGE = 'FLEDGED_CHICK_STAGE',

  UNKNOWN = 'UNKNOWN',
}
