export const enum HatchType {
  GOOD = 'GOOD',

  NEEDS_EYELETS = 'NEEDS_EYELETS',

  NEEDS_METAL_BAR = 'NEEDS_METAL_BAR',

  NEEDS_FILING = 'NEEDS_FILING',

  ADDED_EYELETS = 'ADDED_EYELETS',

  ADDED_METAL_BAR = 'ADDED_METAL_BAR',

  FILED_HATCH = 'FILED_HATCH',
}
