export const enum ImpactOnMKType {
  UNKNOWN = 'UNKNOWN',

  BREEDING_MALE_MK_DELAYED_ENTERING_NEST = 'BREEDING_MALE_MK_DELAYED_ENTERING_NEST',

  BREEDING_FEMALE_MK_DELAYED_ENTERING_NEST = 'BREEDING_FEMALE_MK_DELAYED_ENTERING_NEST',

  BREEDING_MALE_MK_DELAYED_LEAVING_NEST = 'BREEDING_MALE_MK_DELAYED_LEAVING_NEST',

  BREEDING_FEMALE_MK_DELAYED_LEAVING_NEST = 'BREEDING_FEMALE_MK_DELAYED_LEAVING_NEST',

  MK_CANT_ACCESS_NEST = 'MK_CANT_ACCESS_NEST',

  MK_CHASING_COMPETITOR = 'MK_CHASING_COMPETITOR',

  BREEDING_MALE_MK_CHASING_COMPETITOR = 'BREEDING_MALE_MK_CHASING_COMPETITOR',

  BREEDING_FEMALE_MK_CHASING_COMPETITOR = 'BREEDING_FEMALE_MK_CHASING_COMPETITOR',

  MK_BREEDING_PAIR_CHASING_COMPETITOR = 'MK_BREEDING_PAIR_CHASING_COMPETITOR',

  MK_FIGHTING_COMPETITOR = 'MK_FIGHTING_COMPETITOR',

  BREEDING_MALE_MK_FIGHTING_COMPETITOR = 'BREEDING_MALE_MK_FIGHTING_COMPETITOR',

  BREEDING_FEMALE_MK_FIGHTING_COMPETITOR = 'BREEDING_FEMALE_MK_FIGHTING_COMPETITOR',

  NEST_SITE_OCCUPIED = 'NEST_SITE_OCCUPIED',
}
