export const enum PreySpeciesType {
  UNKNOWN = 'UNKNOWN',

  PHELSUMA_SPP = 'PHELSUMA_SPP',

  PHELSUMA_CEPEDIANA = 'PHELSUMA_CEPEDIANA',

  PHELSUMA_ORNATA = 'PHELSUMA_ORNATA',

  PHELSUMA_GUMBEAUI = 'PHELSUMA_GUMBEAUI',

  PHELSUMA_ROSAGULARIS = 'PHELSUMA_ROSAGULARIS',

  HOUSE_GECKO = 'HOUSE_GECKO',

  AGAMID_LIZARD = 'AGAMID_LIZARD',

  GREY_WHITE_EYE = 'GREY_WHITE_EYE',

  MADAGASCAR_FODY = 'MADAGASCAR_FODY',

  RED_WHISKERED_BULBUL = 'RED_WHISKERED_BULBUL',

  WAXBILL = 'WAXBILL',

  ZEBRA_DOVE = 'ZEBRA_DOVE',

  YELLOW_FRONTED_CANARY = 'YELLOW_FRONTED_CANARY',

  ASIAN_MUSK_SHREW = 'ASIAN_MUSK_SHREW',

  BLACK_RAT = 'BLACK_RAT',

  BROWN_RAT = 'BROWN_RAT',

  DRAGONFLY = 'DRAGONFLY',

  STICK_INSECT = 'STICK_INSECT',

  CICADA = 'CICADA',
}
