export const enum SeenDuringType {
  OPPORTUNISTIC = 'OPPORTUNISTIC',

  PRE_SEASON = 'PRE_SEASON',

  EGG_CHECK = 'EGG_CHECK',

  HATCH_CHECK = 'HATCH_CHECK',

  RINGING = 'RINGING',

  FLEDGE_CHECK = 'FLEDGE_CHECK',

  MAINTENANCE = 'MAINTENANCE',

  WATCH = 'WATCH',
}
