export const enum UseSignType {
  MUTES = 'MUTES',

  SCRAPE = 'SCRAPE',

  SCRAPE_FLATTENED = 'SCRAPE_FLATTENED',

  RECENT_SCRAPE = 'RECENT_SCRAPE',

  DOWN_FEATHERS = 'DOWN_FEATHERS',

  FEATHERS = 'FEATHERS',

  PELLETS = 'PELLETS',

  MULTIPLE_SIGNS = 'MULTIPLE_SIGNS',
}
